version: '2'
services:
    camunda-mysql:
            image: mysql:5.7.20
            volumes:
                - ~/volumes/jhipster/camunda-mysql/mysql/:/var/lib/mysql/
            environment:
                - MYSQL_USER=root
                - MYSQL_ROOT_PASSWORD=root
                - MYSQL_DATABASE=camunda_db
            ports:
                - 33060:3306
            command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
